apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: edns-{{ .Values.vs.name }}
  labels:
    f5cr: "true"
spec:
  domainName: {{ .Values.vs.fqdn }}
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/gtm-primary
    monitor:
      type: tcp
      interval: 3
      timeout: 10
