apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: {{ .Values.vs.name }}
spec:
  ipamLabel: {{ .Values.vs.ipamlabel }}
  host: {{ .Values.vs.fqdn }}
  virtualServerPort: 80
  virtualServerName: vs-{{ .Values.vs.name }}
  mode: standard
  snat: auto
  pool:
    service: {{ .Values.vs.service }}
    servicePort: 80
    monitor:
      type: tcp
      interval: 3
      timeout: 10
